name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest -C Release --output-on-failure
        working-directory: build

      - name: Package
        run: cmake --build build --config Release --target package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-sandtimer-windows
          path: build/mcp-sandtimer-*.zip

      - name: Publish release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/mcp-sandtimer-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
